CREATE SEQUENCE ACCOUNT_ID_SEQUENCE START WITH 1;

CREATE TABLE ACCOUNT
(
    ACCOUNT_ID      BIGINT,
    ACCOUNT_NAME    VARCHAR,
    ACCOUNT_BALANCE DECIMAL(7, 2),

    PRIMARY KEY (ACCOUNT_ID),
    UNIQUE (ACCOUNT_NAME)
);
